name: PR Code Quality and Vulnerability Scan

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: shellcheck cloudflare-ddns/cloudflare_ddns.sh

      - name: Run Hadolint
        run: docker run --rm -i -v "${PWD}/cloudflare-ddns/Dockerfile:/Dockerfile" hadolint/hadolint < /Dockerfile

  build-and-scan:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (for pulling base images)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build PR Docker image
        id: build-pr-image
        uses: docker/build-push-action@v5
        with:
          context: ./cloudflare-ddns
          push: false # Only build for scanning, do not push
          tags: ${{ env.DOCKER_IMAGE_NAME }}:pr-${{ github.event.pull_request.number || github.sha }}
          platforms: linux/amd64,linux/arm64
          load: true # Load image to be able to scan it locally

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE_NAME }}:pr-${{ github.event.pull_request.number || github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH' 